spring.application.name=leetcoach

# Local MongoDB Connection
spring.data.mongodb.uri=mongodb://localhost:27017/leetcoach_db
spring.data.mongodb.database=leetcoach_db

# Server Port
server.port=8080
logging.level.org.springframework.security=DEBUG


spring.security.user.name=admin
spring.security.user.password=admin123
