spring.application.name=leetcoach

# Local MongoDB Connection
spring.data.mongodb.uri=mongodb://localhost:27017/leetcoach_db
spring.data.mongodb.database=leetcoach_db

# Server Port
server.port=8080

# Spring Security (test login)
spring.security.user.name=admin
spring.security.user.password=admin123
spring.security.user.roles=ADMIN